apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiitb-community-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: durgaprasad81/iiitb-community-backend:latest
          ports:
            - containerPort: 3333
          env:
            - name: SECRET_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: SECRET_ACCESS_TOKEN
            - name: SECRET_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: SECRET_REFRESH_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: JWT_SECRET
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: MONGODB_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: DATABASE_NAME
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: iiitb-backend-secret
                  key: NODE_ENV


---

apiVersion: v1
kind: Service
metadata:
  name: iiitb-community-backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
