apiVersion: v1
kind: Secret
metadata:
  name: iiitb-backend-secret
type: Opaque
data:
  SECRET_ACCESS_TOKEN: MGY3MGE5OTYzMDAxMjhiY2ZkZjcxZDAwZDcxMjIyOGFlZTdmMWFiYTE2NDc1NWYwNDY2NzVmYzZhMTdjODFhODBkZGJkYzM0YWZiMmZhYmQzNGMyZjgzZDE4MjMyMTk3MDIzMzJhY2U4NzdmN2ZjNzIwZDZhODhjYzIwN2ZkZmQ=
  SECRET_REFRESH_TOKEN : MWVkZjBlODM1YTZhZjRjMmUzMmQ5ZjljMGJjODZlZWZlY2Y4Njg5YzYxYmE5YWExNWU3YmFjOGZhODAxMjU1N2QwMzM4NWJhNWQ1NTQ3NGEwYjg1MjZhNmIyNmUxMzNiMjZhNDBlMDkxZDhiNmVhNzhhMjQ2NTk3OWZlODk4ZDk=
  JWT_SECRET : MGY3MGE5OTYzMDAxMjhiY2ZkZjcxZDAwZDcxMjIyOGFlZTdmMWFiYTE2NDc1NWYwNDY2NzVmYzZhMTdjODFhODBkZGJkYzM0YWZiMmZhYmQzNGMyZjgzZDE4MjMyMTk3MDIzMzJhY2U4NzdmN2ZjNzIwZDZhODhjYzIwN2ZkZmQ=
  MONGODB_PASSWORD : bkRFUzN6MXpkZXp3WUgwag==
  DATABASE_NAME : dGVzdA==
  DATABASE_URL : bW9uZ29kYitzcnY6Ly9yYW1zcmVla2FyMDkyOTpuREVTM3oxemRlendZSDBqQG15Y2x1c3Rlci53dGd4MC5tb25nb2RiLm5ldC90ZXN0P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  NODE_ENV : cHJvZHVjdGlvbg==