---
- name: Deploy backend app to minikube
  hosts: all
  tasks:
    - name: delete previous backend deployment
      shell: kubectl get deployment iiitb-backend-deployment >/dev/null 2>&1 && kubectl delete deployment iiitb-backend-deployment || echo "deployment not found, skipping delete"

    - name: delete previous secret
      shell: kubectl get secret iiitb-backend-secret >/dev/null 2>&1 && kubectl delete secret iiitb-backend-secret || echo "secret not found, skipping delete"

    - name: apply secret
      shell: kubectl apply -f ../secret.yml

    - name: apply backend
      shell: kubectl apply -f ../backend_deployment.yml